### GET all books
GET http://localhost:3000/books

### GET a single book by ID
GET http://localhost:3000/books/668430f503a3f8478b95fbd4

### POST create a new book
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Livro ESTG",
  "author": "John Doe",
  "category": "Informatics",
  "totalCopies": 4
}

### PUT update a book by ID
PUT http://localhost:3000/books/668430f503a3f8478b95fbd4
Content-Type: application/json

{
  "title": "Updated Book Title"
}

### DELETE a book by ID
DELETE http://localhost:3000/books/66841f76fddf4563d622449b

### GET books by title
GET http://localhost:3000/books?title=João

### GET books by author
GET http://localhost:3000/books?author=Doe

### GET books by category
GET http://localhost:3000/books?category=Fiction
